#!/bin/bash
#
# Regards, the Alveare Solutions society.
#
declare -A HR_DEFAULT
declare -A HR_LIB
declare -A HR_SOURCE
declare -A HR_DECOMPOSE

if [ $EUID -ne 0 ]; then
    echo "[ WARNING ]: HellRot requiers elevated privileges. Are you root?"
    exit 1
fi

# [ NOTE ]: Absolute directory path the current file is in.
HR_DIRECTORY="$(
    cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd
)"
CONF_FILE_PATH="$HR_DIRECTORY/conf/hell-rot.conf"

if [ ! -f "$CONF_FILE_PATH" ]; then
    echo "[ WARNING ]: Config file ($CONF_FILE_PATH) not found."
    return 1
else
    source "$CONF_FILE_PATH"
fi

for script in ${!HR_SOURCE[@]}; do
    source ${HR_SOURCE[$script]}
    if [ $? -ne 0 ]; then
        echo "[ NOK ]: Something went wrong."\
            "Could not load ($script) script (${HR_SOURCE[$script]})."
    else
        echo "[ OK ]: Successfully loaded ($script) script"\
            "(${HR_SOURCE[$script]})."
    fi
done

for library in ${!HR_LIB[@]}; do
    source ${HR_LIB[$library]}
    if [ $? -ne 0 ]; then
        echo "[ NOK ]: Something went wrong."\
            "Could not load ($library) library."
    else
        echo "[ OK ]: Successfully loaded ($library) library."
    fi
done

# MISCELLANEOUS

function init_hellrot () {
    hellrot_project_setup
    display_hellrot_banner
    init_menu 'MainController'
}

init_hellrot
